version: '3.3'
services:
  client:
    build:
      context: ./
    command: "build:dev"
    volumes:
      - ./:/app
      - ./dist:/home/node/app/dist
      - ./node_modules:/home/node/app/node_modules
  

volumes:
  dist:
  node_modules: